version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  apt_packages:
    - graphviz
  jobs:
    pre_install:
      - pip install furo
      - pip install breathe
      - export PATH="/usr/bin/:$PATH"

sphinx:
  builder: html
  configuration: ./docs/Sphinx/conf.py
  # fail_on_warning: true

# Build PDF & ePub
formats:
  - epub
  - pdf
